---
title: Data Science - Why am I doing this?
author: Florian Handke
date: '2020-06-09'
slug: am-i-doing-this
categories:
  - Data Science
tags:
  - insight
  - '2020'
subtitle: ''
summary: ''
authors: []
lastmod: '2020-06-09T21:23:07+02:00'
featured: no
image:
  caption: ''
  focal_point: ''
  preview_only: no
projects: []
---

I mean, five years ago, I never thought I'd be at this point. 
It's not like I have several patents pending. No I am a data scientist.

But what does that even mean. And why did someone like me suddenly enjoy evaluating data?
In every blog post and every other industry article, 
people talk about data and its importance for the future. Everything will be 
based only on data, the unknown machine will make decisions and we will be surprised how good these decisions are.

Please do not misunderstand me: I believe data is an important basis for 
understanding and optimizing business processes. 
They are the basis for new services, help to optimize products and sometimes look pretty cool :)

You may remember the world map which shows the user interaction of 
Facebook users worldwide. Or other unusual ways of processing and displaying data.

What I learned about Data Science is that it takes much more than data. 
What it needs most of all is a problem definition, domain knowledge 
from people who are experts in their field and an understanding of what the target audience wants to know.
If I then have the necessary mathematical understanding, I am ready for the big, wide Data Science world.

Then the fun begins: In my time as a data scientist 
I have almost never seen a data set that didn't have data quality problems. 
Missing data, unrealistic data, wrong timestamps, data gaps, etc.. 
No matter whether they are made by humans or by a machine. 
Such quality problems can leave you living in an illusion until the end. 
An illusion that perhaps says that it would be a good decision 
to increase inventory, sell a product or send a service technician on site.

As soon as all this has been fixed, we'll move on: classification, forecast, decision trees.

So what if I told you that much of what a data scientist does is not 
about complicated forecasting procedures, but about preparing, structuring, aggregating data and ensuring reproducibility.

Only then one can think about the type of visualization or application of machine learning.

I think it is worth thinking about real profitable projects. To think big but start small. 

Perhaps it might be quite impressive to make a prediction about the spontaneous failure of a system. But it is more likely that there are much simpler questions to solve which also bring a greater benefit in everyday life.
